---
variables:
  # Change pip's cache directory to be inside the project directory since we
  # can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

image: "python:3.9-slim"

cache:
  key:
    files:
      - pyproject.toml
      - poetry.lock
  paths:
    - .cache/pip
    - .venv/

before_script:
  - apt-get update
  - apt-get install make
  - pip install poetry
  - poetry config virtualenvs.in-project true

build:
  stage: build
  script:
    - poetry install

lint:
  stage: test
  script:
    # if no global cache servers are registered we might need to reinstall the
    # project
    - "[ ! -d .venv ] && poetry install"
    - poetry run make lint
format:
  stage: test
  script:
    # if no global cache servers are registered we might need to reinstall the
    # project
    - "[ ! -d .venv ] && poetry install"
    - poetry run make format-check
mypy:
  stage: test
  script:
    # if no global cache servers are registered we might need to reinstall the
    # project
    - "[ ! -d .venv ] && poetry install"
    - poetry run make mypy
