name: GitHub Actions - Basic checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      with:
        path: | 
          .venv/
          ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools poetry
        poetry config virtualenvs.in-project true
        poetry install
    - name: Run linters
      run: |
        make lint
    - name: Check formatting
      run: |
        make format-check
    - name: Check static type hints
      run: |
        make mypy
